# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 1
/tracking/verbose 0
# 
# muon 1000 MeV to the direction (0.,0.,1.)
#
/gun/particle mu-
/gun/energy 100 MeV
/tracking/verbose 2
#
/run/beamOn 3
